### ISSUE TITLE
リンク切れのURLが本文中に存在するとエラーが出る。

### ISSUE THREAD

**Issue by mu60** [yosiakatsuki/ystandard#480]
【テーマ・プラグイン】
yStandard

【WordPressバージョン】
6.0.2

【テーマ・プラグインバージョン】
4.36.2

yStandardが有効だとブロックエディターにて記事編集中、URLを本文に貼り付けると「ys_blog_card」というショートコードに自動変換されます。
しかし、リンク切れのURLが入力されていると、記事をプレビューもしくは公開してから記事ページを開いたときに、本文の冒頭に下記のようなエラーメッセージが表示されてしまいます。
また、リンク切れだけでなく、wikipediaなどの現存しているリンクでも同様のエラーが発生します。

`Warning: Undefined array key "title" in /home/xxxxxxxxx/public_html/xxxxxxxxxxxxxxxx.com/wp-content/themes/ystandard/inc/blog-card/class-blog-card.php on line 258

Warning: Undefined array key "dscr" in /home/xxxxxxxxx/public_html/xxxxxxxxxxxxxxxx.com/wp-content/themes/ystandard/inc/blog-card/class-blog-card.php on line 264

Warning: Undefined array key "thumbnail" in /home/xxxxxxxxx/public_html/xxxxxxxxxxxxxxxx.com/wp-content/themes/ystandard/inc/blog-card/class-blog-card.php on line 280`

このようなエラー文を非表示にすることは可能でしょうか？
または、画像つきリンクが表示されるはずだった箇所へ、代わりにリンク切れの案内を出すことはできますか？

**Comment by mu60** [comment]
さっそくのご回答ありがとうございました。
yStanddard Blocksのカードブロックを使うことで、望みどおりの表示を実現することができました。
ただ、各記事に設置済みのys_blog_cardショートコードをすべて、カードブロックに置き換えたいと思ったのですが、すでに膨大な数の記事が存在しているため、手作業で置き換えるのが大変です。
やはり一括置き換えは、Search Regexなどで対処するしかないでしょうか？

**Comment by yosiakatsuki** [comment]
ありがとうございます！
エラー対処については引き続き進めますのでお待ち下さい。

ショートコードのブロックへの変換は大変ですが手動でやっていただいたほうが確実です…
一括変換をする場合は正規表現置換などやや難しい対応が必要になるかと思います

よろしくおねがいします！
