### ISSUE TITLE
ultimate  memberプロフィールページで記事一覧の絞り込みでエラーが発生する場合がある

### ISSUE THREAD

**Issue by yosiakatsuki** [yosiakatsuki/ystandard#500]
不具合報告を受け付けました。

【テーマ・プラグイン】
ystandard子テーマ

【WordPressバージョン】
6.2

【テーマ・プラグインバージョン】
4.44.0

【不具合の詳細】
【テーマの$term_ids 変数に関するエラー】

エラーはプラグインultimate  memberのプロフィールページで起きました。

具体的には、ultimate  memberのプロフィールにbbressで投稿されたトピック一覧等が表示できる、拡張プラグインum-bbressというプラグインとの相性が悪い？らしくエラーメッセージが表示されています。

管理者のアカウントでは、エラーは表示されませんが、権限が購読者のユーザーにエラーが表示されています。

PHPのスクリプトで変数 $term_ids が未定義なことが原因のようです。

【使用しているプラグインの一覧】
・bbpress
・ultimate  member
・um-bbress(ultimate  memberの拡張プラグイン)

【エラーメッセージ】
Warning: Undefined variable $term_ids in /home/〇〇/[〇〇.com/public_html/wp-content/themes/ystandard/inc/content/class-recent-posts.php](http://xn--w6ja.com/public_html/wp-content/themes/ystandard/inc/content/class-recent-posts.php) on line 550

(IDとドメインを〇〇にしております。)

**Comment by fanlycm** [comment]
こんにちは
こちら投稿したものです。

テーマファイルを編集するのは避けたいので、アップデートされる?かはわかりませんが一旦
デバックモードで無効化する形で消しておいた方が良いでしょうか？

**Comment by yosiakatsuki** [comment]
@fanlycm ありがとうございます
対応遅れてしまい、失礼いたしました。
一旦、エラーメッセージを表示しないようにできるのであれば、暫定対応としてテーマファイルの修正等で対応をおねがいします

**Comment by fanlycm** [comment]
親テーマで以下のようなコードに変更すれば、一応消せたのですが問題ありそうでしょうか・・・
(ここでお答えできない場合は大丈夫です。急な質問ですみません)

`private function get_the_term_ids( $taxonomy ) {
    $parent = [];
    $term_ids = [];  // 新しく追加した行

    if ( is_tax( $taxonomy ) ) {
        $term       = get_queried_object();
        $parent[]   = $term->term_id;
        $term_ids[] = $term->term_id;
    } elseif ( is_single() ) {
        $term = get_the_terms( false, $taxonomy );
        if ( is_wp_error( $term ) || ! $term ) {
            return [];
        }
        foreach ( $term as $term_obj ) {
            $parent[]   = $term_obj->term_id;
            $term_ids[] = $term_obj->term_id;
        }
    }
    foreach ( $parent as $id ) {
        $children = get_term_children( (int) $id, $taxonomy );
        $term_ids = array_merge( $term_ids, $children );
    }

    return $term_ids;
}
`

**Comment by yosiakatsuki** [comment]
@fanlycm ありがとうございます！
上記修正で問題ありません！
テーマ側も同様の修正が入ります！

**Comment by yosiakatsuki** [comment]
v4.45.0にて対処いたしました

**Comment by fanlycm** [comment]
ありがとうございます！！無事反映されてました！
