### ISSUE TITLE
bbPressのトピックでURLの書き込みが自動的にブログカードのショートコードになってしまう

### ISSUE THREAD

**Issue by yosiakatsuki** [yosiakatsuki/ystandard#501]
不具合報告を受け付けました。

【テーマ・プラグイン】
ystandard

【WordPressバージョン】
6.2

【テーマ・プラグインバージョン】
ystandard-childバージョン: 4.0.0

【不具合の詳細】
[ys_blog_card]の不具合について

投稿ページや固定ページにURLを貼り付けると、自動的にブログカードになるとても便利なショートコードですが、bbPressなどのトピック(返信)でURLが貼られた場合以下のようにそのまま表示されてしまいます。

[ys_blog_card url="https://wp-ystandard.com/"]

トピックは投稿や固定ページと違ってユーザーが投稿するため、投稿時に修正を加えられません、
bbpressで表示されないようにする、または投稿ページ・固定ページでは、[ys_blog_card]が反映されないように不具合を治すことはできないのでしょうか

【使用しているプラグインの一覧】

【エラーメッセージ】

**Comment by yosiakatsuki** [comment]
プラグインとの相性になるため、テーマ側にプラグインに対応するためのコードを書いて対応はできません。

bbPressのトピックでショートコードが実行できるようにカスタマイズが可能か検討してみてください。

昨今、ほとんどのサイトでブロックが使われていると思うので、URLをブログカード用ショートコードに変換する機能はオプトイン方式にしても良いかもしれないので検討します

**Comment by fanlycm** [comment]
初めまして、報告をしたものです。
検討いただきありがとうございます。
一旦以下のようなPHPで、ys_blog_cardのみを許可する形にしてみました。
一応問題なく表示されているようです🙇‍♂️


```
function bbp_enable_specific_shortcodes($content){
    // リストにあるショートコードだけを許可します
    $shortcodes = array(
        'ys_blog_card'
    );
​
    // ショートコードを展開する

    foreach ($shortcodes as $shortcode) {

        if (has_shortcode($content, $shortcode)) {
            $content = do_shortcode($content);
            break;
        }
    }
    return $content;
}
add_filter('bbp_get_topic_content', 'bbp_enable_specific_shortcodes');
add_filter('bbp_get_reply_content', `'bbp_enable_specific_shortcodes');
```

**Comment by yosiakatsuki** [comment]
@fanlycm ありがとうございます！
ひとまず解決されたとのことでホッとしました！
引き続き、自動変換を有効化する・しないの設定追加は検討したいと思います（ほぼ設定追加する予定です）

よろしくお願いします！

**Comment by yosiakatsuki** [comment]
v4.45.0で自動変換ON・OFFを切り替えられる設定を追加しました
https://wp-ystandard.com/ystandard-v4-45/
