### ISSUE TITLE
ヘッダーサムネイルテンプレートにフックがほしい

### ISSUE THREAD

**Issue by yosiakatsuki** [yosiakatsuki/ystandard#522]
対象ファイル： `/template-parts/parts/header-thumbnail.php`

```
if ( empty( $header_thumbnail ) ) {
	return;
}
?>

<figure class="site-header-thumbnail">
→この位置の予定
	<?php echo $header_thumbnail; ?>
</figure>
```

**Comment by mypacecreator** [comment]
言い出しっぺで恐縮ですが、アクションフックだとimgの上がいい、下がいい、など人によって要望が変わりそうなので、やみくもにフックを増やすよりも`ys_get_header_post_thumbnail` でやってもらうようにしたほうがきれいだろうなぁ、と思いました🙇‍♀️クローズいただいても大丈夫です

**Comment by yosiakatsuki** [comment]
ありがとうございます！

上がいい・下がいい…もあるからアクションフック追加するなら両方にあったほうがいいな…
でも、それならフィルターフックにしたほうが1個ですむからスッキリするなぁ…
でも、フック初心者からするとフィルターでreturn忘れると途端に何も表示されなくなって混乱するかもだからアクションフックのほうがいいかなぁ…
それなら、アクションフックのほうがいいかぁ…
でも、そしたら上下で2つ用意する？ここにほんとに2つもいるかなぁ…
うーん…一旦1個追加して要望があれば追加でもいいかなぁ…

…みたいな感じだったので、今回は一旦見送りにします！
