### ISSUE TITLE
WordPress 6.7 で wp_targeted_link_rel, wp_targeted_link_rel_callback がDeprecatedになったことによるエラー表示

### ISSUE THREAD

**Issue by mypacecreator** [yosiakatsuki/ystandard#523]
WordPress 6.7 + yStandard 4.51.0 の環境で、管理画面でエラーが出るようになりました。

```
Deprecated: 関数 wp_targeted_link_rel は、バージョン 6.7.0 から非推奨になり、代替手段がなくなりました。 in /wp-includes/functions.php on line 6114

Deprecated: 関数 wp_targeted_link_rel_callback は、バージョン 6.7.0 から非推奨になり、代替手段がなくなりました。 in //wp-includes/functions.php on line 6114
```

コードを追ってみたところ、compatibility.php 上で wp_targeted_link_rel の互換性対応は入ってたんですが、wp_targeted_link_rel_callback がないことが原因かも？と思いました（未検証）。

https://github.com/yosiakatsuki/ystandard/blob/357f0f08b1bc855cc64c00299a1e7a1361c01ce1/inc/compatibility/compatibility.php#L20C1-L33C1

![Screenshot by Dropbox Capture](https://github.com/user-attachments/assets/3d2a9b4b-e1a3-4889-b323-2eca091456b2)

※5.1で導入→6.7でDeprecatedって短命ですね。。。

**Comment by yosiakatsuki** [comment]
@mypacecreator ありがとうございます！
確認します！
（これが見えていない自分の開発環境がめちゃめちゃ怪しい気がしてきました…Wraning表示消した記憶は無いのですが…）
